apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: whoami
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: whoami
  pollingInterval: 10
  minReplicaCount: 0
  maxReplicaCount: 10
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
          - type: Percent
            value: 100
            periodSeconds: 10
  triggers:
  - type: rabbitmq
    metadata:
      mode: QueueLength
      queueName: demo_queue
      value: "10"
      vhostName: /
      hostFromEnv: KEDA_RABBITMQ_URI
